Repository EcoFriendly-Recycle/ECOECO, pull requests merged in 2024-04, with the labels that each got.

#1 비밀번호찾기 기능구현 완료
  build.gradle
  src/main/java/com/recycle/ecoeco/membership/controller/user/MyPageController.java
  src/main/java/com/recycle/ecoeco/membership/model/dao/user/MypageMapper.java
  src/main/java/com/recycle/ecoeco/membership/service/user/EmailService.java
  src/main/java/com/recycle/ecoeco/membership/service/user/MyPageService.java
  src/main/java/com/recycle/ecoeco/membership/service/user/PasswordGenerator.java
  src/main/resources/application.yml
  src/main/resources/mappers/user/MypageMapper.xml
  src/main/resources/static/css/user/mypage/searchid.css
  src/main/resources/static/js/user/mypage/findUser.js
  src/main/resources/templates/joinus.html
  src/main/resources/templates/user/mypage/findPwd.html
Labels: 기능구현잇슈, 김대한

#17 관리자:게시판 이미지 첨부/수정
  dbsql/ECOECO_DB_(v8.7).sql
  src/main/java/com/recycle/ecoeco/board/notice/controller/manager/AdminNoticeController.java
  src/main/java/com/recycle/ecoeco/board/notice/model/dao/manager/AdminNoticeMapper.java
  src/main/java/com/recycle/ecoeco/board/notice/model/dto/NoticeDTO.java
  src/main/java/com/recycle/ecoeco/board/notice/model/dto/NoticeImageDTO.java
  src/main/java/com/recycle/ecoeco/board/notice/service/manager/AdminNoticeService.java
  src/main/java/com/recycle/ecoeco/board/usGreen/controller/manager/AdminUsGreenController.java
  src/main/java/com/recycle/ecoeco/common/paging/Pagenation.java
  src/main/java/com/recycle/ecoeco/common/paging/SelectCriteria.java
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserInfoDTO.java
  src/main/java/com/recycle/ecoeco/membership/service/user/MyPageService.java
  src/main/resources/application.yml
  src/main/resources/mappers/manager/AdminNoticeMapper.xml
  src/main/resources/mappers/manager/AdminUsGreenMapper.xml
  src/main/resources/static/css/manager/adminNotice.css
  src/main/resources/static/css/manager/notice.css
  src/main/resources/static/js/manager/board/boardEvent.js
  src/main/resources/static/uploadFiles/notice/144ea397-0389-47be-839b-b134c6610720.jpg
  src/main/resources/static/uploadFiles/notice/1cd83f61-a506-4e46-a658-a253d519ae89.png
  src/main/resources/static/uploadFiles/notice/e20ce95a-d5c9-4fc3-ba8f-e53e3b914f0f.png
  src/main/resources/templates/adminMain.html
  src/main/resources/templates/manager/board/adminNoticeDetail.html
  src/main/resources/templates/manager/board/adminNoticeList.html
  src/main/resources/templates/manager/board/adminNoticeModify.html
  src/main/resources/templates/manager/board/adminNoticeWrite.html
  src/main/resources/templates/manager/board/adminUsGreenDetail.html
  src/main/resources/templates/manager/board/adminUsGreenList.html
Labels: 기능구현잇슈, 이유란

#18 Noodle/project
  src/main/java/com/recycle/ecoeco/accounting/controller/AdminOrderController.java
  src/main/java/com/recycle/ecoeco/accounting/controller/AdminSettlementController.java
  src/main/java/com/recycle/ecoeco/accounting/model/dao/manager/AdminOrderMapper.java
  src/main/java/com/recycle/ecoeco/accounting/service/AdminOrderService.java
  src/main/java/com/recycle/ecoeco/makerProject/controller/user/SubFileUploadController.java
  src/main/java/com/recycle/ecoeco/makerProject/controller/user/UserProjectController.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dao/user/UserProjectMapper.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/CategoryDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/MakerDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/NewsDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/ProjectDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/RewardDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/StoryDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/StoryRepImgDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/service/manager/AdminProjectService.java
  src/main/java/com/recycle/ecoeco/makerProject/service/user/UserProjectService.java
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserInfoDTO.java
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserRole.java
  src/main/resources/mappers/UserProjectMapper.xml
  src/main/resources/static/css/user/common/header.css
  src/main/resources/static/css/user/sub/maker/maker.css
  src/main/resources/static/css/user/sub/projectInfo/projectInfo.css
  src/main/resources/static/css/user/sub/reward/reward.css
  src/main/resources/static/css/user/sub/story/story.css
  src/main/resources/templates/user/common/header.html
  src/main/resources/templates/user/project/detail/detail-news.html
  src/main/resources/templates/user/project/detail/detail-refund.html
  src/main/resources/templates/user/project/detail/detail-review.html
  src/main/resources/templates/user/project/detail/detail-reward.html
  src/main/resources/templates/user/project/detail/detail.html
  src/main/resources/templates/user/project/maker/maker.html
  src/main/resources/templates/user/project/projectInfo/projectInfo.html
  src/main/resources/templates/user/project/reward/reward.html
  src/main/resources/templates/user/project/story/story.html
  src/main/resources/templates/user/project/terms/terms.html
  src/main/resources/templates/user/sub/projectInfo/projectInfo.html
  src/main/resources/templates/user/sub/story/story.html
Labels: 기능구현잇슈, 신동우

#19 관리자:게시판 이미지 수정/이벤트 구현
  src/main/java/com/recycle/ecoeco/board/notice/controller/manager/AdminNoticeController.java
  src/main/java/com/recycle/ecoeco/board/notice/model/dao/manager/AdminNoticeMapper.java
  src/main/java/com/recycle/ecoeco/board/notice/service/manager/AdminNoticeService.java
  src/main/resources/application.yml
  src/main/resources/mappers/manager/AdminNoticeMapper.xml
  src/main/resources/static/js/manager/board/boardEvent.js
  src/main/resources/templates/manager/board/adminNoticeDetail.html
  src/main/resources/templates/manager/board/adminNoticeModify.html
Labels: 기능구현잇슈, 오류수정햇슈, 이유란

#22 DB 쿼리문 파일
  dbsql/ECOECO_DB_(v9_0430).sql
Labels: 기능구현잇슈, 이유란

#26 관리자 프로젝트 기능 수정, 관리자 결제 및 정산, 회원관리 기능 인계 받아 수정
  src/main/java/com/recycle/ecoeco/accounting/controller/AdminOrderController.java
  src/main/java/com/recycle/ecoeco/accounting/controller/AdminRefundController.java
  src/main/java/com/recycle/ecoeco/accounting/controller/AdminSettlementController.java
  src/main/java/com/recycle/ecoeco/accounting/model/dao/manager/AdminRefundMapper.java
  src/main/java/com/recycle/ecoeco/accounting/model/dao/manager/AdminSettlementMapper.java
  src/main/java/com/recycle/ecoeco/accounting/model/dto/OrderDTO.java
  src/main/java/com/recycle/ecoeco/accounting/model/dto/PaymentDTO.java
  src/main/java/com/recycle/ecoeco/accounting/model/dto/RefundDTO.java
  src/main/java/com/recycle/ecoeco/accounting/model/dto/SettlementDTO.java
  src/main/java/com/recycle/ecoeco/accounting/service/AdminRefundService.java
  src/main/java/com/recycle/ecoeco/accounting/service/AdminSettlementService.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/MakerDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/ReviewDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/StoryDTO.java
  src/main/java/com/recycle/ecoeco/membership/controller/manager/AdminCustomerController.java
  src/main/java/com/recycle/ecoeco/membership/model/dao/manager/AdminCustomerMapper.java
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserInfoDTO.java
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserProfileImageDTO.java
  src/main/java/com/recycle/ecoeco/membership/service/manager/AdminCustomerService.java
  src/main/resources/mappers/manager/AdminCustomerMapper.xml
  src/main/resources/mappers/manager/AdminOrderMapper.xml
  src/main/resources/mappers/manager/AdminPaymentMapper.xml
  src/main/resources/mappers/manager/AdminProjectMapper.xml
  src/main/resources/mappers/manager/AdminRefundMapper.xml
  src/main/resources/mappers/manager/AdminSettlementMapper.xml
  src/main/resources/static/css/manager/sub.css
  src/main/resources/templates/manager/customer/customer_info.html
  src/main/resources/templates/manager/customer/customer_list.html
  src/main/resources/templates/manager/ordertab/order/order_info.html
  src/main/resources/templates/manager/ordertab/order/order_list.html
  src/main/resources/templates/manager/ordertab/payment/payment_info.html
  src/main/resources/templates/manager/ordertab/payment/payment_list.html
  src/main/resources/templates/manager/ordertab/refund/refund_info.html
  src/main/resources/templates/manager/ordertab/refund/refund_list.html
  src/main/resources/templates/manager/ordertab/settlement/settlement_info.html
  src/main/resources/templates/manager/ordertab/settlement/settlement_list.html
  src/main/resources/templates/manager/project/project_detail.html
  src/main/resources/templates/manager/project/project_end_list.html
  src/main/resources/templates/manager/project/project_modify.html
  src/main/resources/templates/manager/project/project_new_list.html
  src/main/resources/templates/manager/project/project_news.html
  src/main/resources/templates/manager/project/project_now_list.html
  src/main/resources/templates/manager/project/project_return_list.html
  src/main/resources/templates/manager/project/project_review.html
Labels: 기능구현잇슈, 김동일, 김우준, 오류수정햇슈
