Repository EcoFriendly-Recycle/ECOECO, pull requests merged in 2024-05, with the labels that each got.

#27 게시판, 쿼리문 업데이트
  dbsql/ECOECO_DB_(v9.1_0430).sql
  src/main/resources/static/uploadFiles/notice/e20ce95a-d5c9-4fc3-ba8f-e53e3b914f0f.png
  src/main/resources/templates/manager/board/adminNoticeDetail.html
  src/main/resources/templates/manager/board/adminNoticeList.html
  src/main/resources/templates/manager/board/adminNoticeModify.html
  src/main/resources/templates/manager/board/adminNoticeWrite.html
  src/main/resources/templates/manager/board/adminUsGreenDetail.html
  src/main/resources/templates/manager/board/adminUsGreenList.html
Labels: 꾸며봣슈, 이유란

#28 커뮤니티 상세 수정
  src/main/resources/templates/manager/board/adminUsGreenDetail.html
Labels: 꾸며봣슈, 이유란

#29 myPage
  src/main/java/com/recycle/ecoeco/accounting/controller/AdminOrderController.java
  src/main/java/com/recycle/ecoeco/accounting/model/dao/manager/AdminOrderMapper.java
  src/main/java/com/recycle/ecoeco/accounting/service/AdminOrderService.java
  src/main/java/com/recycle/ecoeco/common/configuration/SecurityConfig.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/ProjectDTO.java
  src/main/java/com/recycle/ecoeco/membership/controller/user/MyPageController.java
  src/main/java/com/recycle/ecoeco/membership/model/dao/user/MypageMapper.java
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserInfoDTO.java
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserProfileImageDTO.java
  src/main/java/com/recycle/ecoeco/membership/service/user/MyPageService.java
  src/main/resources/mappers/UserProjectMapper.xml
  src/main/resources/mappers/user/MypageMapper.xml
  src/main/resources/static/css/user/mypage/mypagemain.css
  src/main/resources/static/css/user/mypage/searchinfo.css
  src/main/resources/static/images/user/mypage/myPageProfile02.png
  src/main/resources/static/js/user/mypage/checkMyInfo.js
  src/main/resources/static/js/user/mypage/headerAfterLogin.js
  src/main/resources/static/js/user/mypage/joinus.js
  src/main/resources/static/js/user/mypage/login.js
  src/main/resources/static/js/user/mypage/mypage.js
  src/main/resources/templates/joinus.html
  src/main/resources/templates/login.html
  src/main/resources/templates/user/common/header.html
  src/main/resources/templates/user/mypage/findId.html
  src/main/resources/templates/user/mypage/findPwd.html
  src/main/resources/templates/user/mypage/findSearchInfo.html
  src/main/resources/templates/user/mypage/mypageMain.html
  src/main/resources/templates/user/mypage/mypageMain_Maker.html
  src/main/resources/templates/user/mypage/mypage_CheckMyInfo.html
  src/main/resources/templates/user/mypage/mypage_MyProject.html
  src/main/resources/templates/user/mypage/mypage_MyprojectList.html
  src/main/resources/templates/user/mypage/mypage_MyprojectList_Detail.html
  src/main/resources/templates/user/mypage/mypage_SideBar.html
  src/main/resources/templates/user/mypage/mypage_SupportProject.html
  src/main/resources/templates/user/mypage/mypage_SupportProject_Detail.html
  src/main/resources/templates/user/mypage/news.html
  src/main/resources/templates/user/mypage/payment_Status.html
  src/main/resources/templates/user/mypage/registNews.html
  src/main/resources/templates/user/mypage/registNewsDetail.html
  src/main/resources/templates/user/mypage/settlement_Info.html
  src/main/resources/templates/user/mypage/settlement_Info_Details.html
Labels: 기능구현잇슈, 김대한

#33 myPage
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserInfoDTO.java
  src/main/resources/static/js/user/mypage/joinus.js
  src/main/resources/templates/joinus.html
  src/main/resources/templates/login.html
  src/main/resources/templates/user/common/header.html
  src/main/resources/templates/user/mypage/settlement_Info_Details.html
Labels: 기능구현잇슈, 김대한

#34 2024년 5월 1일 메인페이지, 결제
  src/main/java/com/recycle/ecoeco/accounting/controller/user/PaymentController.java
  src/main/java/com/recycle/ecoeco/accounting/model/dao/PaymentMapper.java
  src/main/java/com/recycle/ecoeco/accounting/model/dto/KakaoDTO.java
  src/main/java/com/recycle/ecoeco/accounting/service/user/PaymentService.java
  src/main/java/com/recycle/ecoeco/board/notice/controller/user/NoticeController.java
  src/main/java/com/recycle/ecoeco/board/usGreen/controller/user/UsGreenController.java
  src/main/java/com/recycle/ecoeco/common/main/controller/MainController.java
  src/main/java/com/recycle/ecoeco/common/main/service/MainService.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dao/user/MainMapper.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/ProjectDTO.java
  src/main/resources/mappers/user/MainMapper.xml
  src/main/resources/mappers/user/PaymentMapper.xml
  src/main/resources/mappers/user/UsGreenMapper.xml
  src/main/resources/static/css/user/borad/faqDetailsPage.css
  src/main/resources/static/css/user/borad/faqPage.css
  src/main/resources/static/css/user/borad/makerFaq.css
  src/main/resources/static/css/user/borad/notice.css
  src/main/resources/static/css/user/borad/noticeClickDetailPage.css
  src/main/resources/static/css/user/borad/supporterFaq.css
  src/main/resources/static/css/user/main/crowdfundingPage.css
  src/main/resources/static/css/user/main/faqDetailsPage.css
  src/main/resources/static/css/user/main/faqPage.css
  src/main/resources/static/css/user/main/integratedSearchResultsPage.css
  src/main/resources/static/css/user/main/main.css
  src/main/resources/static/css/user/payment/crowdfundingPage.css
  src/main/resources/static/css/user/payment/prepaymentCompletePage.css
  src/main/resources/static/css/user/usgreen/usGreenWritePage.css
  src/main/resources/static/js/notice/user/notice.js
  src/main/resources/static/js/payment/user/crowdfundingPage.js
  src/main/resources/static/js/usGreen/user/usGreenWritePage.js
  src/main/resources/templates/main.html
  src/main/resources/templates/user/borad/faqDetailsPage.html
  src/main/resources/templates/user/borad/faqPage.html
  src/main/resources/templates/user/borad/makerFaq.html
  src/main/resources/templates/user/borad/notice.html
  src/main/resources/templates/user/borad/noticeClickDetailPage.html
  src/main/resources/templates/user/borad/supporterFaq.html
  src/main/resources/templates/user/category.html
  src/main/resources/templates/user/common/header.html
  src/main/resources/templates/user/main/crowdfundingPage.html
  src/main/resources/templates/user/main/faqDetailsPage.html
  src/main/resources/templates/user/main/faqPage.html
  src/main/resources/templates/user/payment/crowdfundingPage.html
  src/main/resources/templates/user/payment/kakaoPayment.html
  src/main/resources/templates/user/payment/prepaymentCompletePage.html
  src/main/resources/templates/user/section.html
  src/main/resources/templates/user/usgreen/usGreenWritePage.html
Labels: 김민준

#35 myPage
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/MakerDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/NewsDTO.java
  src/main/java/com/recycle/ecoeco/membership/controller/user/MyPageController.java
  src/main/resources/mappers/user/MypageMapper.xml
  src/main/resources/static/css/user/common/header.css
  src/main/resources/static/js/user/mypage/mypage.js
  src/main/resources/templates/user/common/header.html
  src/main/resources/templates/user/mypage/mypage_MyProject.html
  src/main/resources/templates/user/mypage/news.html
  src/main/resources/templates/user/mypage/settlement_Info_Details.html
Labels: 기능구현잇슈, 김대한

#38 UserInfoDTO 변경 부분 수정
  src/main/java/com/recycle/ecoeco/membership/model/dto/UserInfoDTO.java
  src/main/resources/mappers/manager/AdminProjectMapper.xml
Labels: 김동일, 오류수정햇슈

#39 최종 완료
  src/main/java/com/recycle/ecoeco/makerProject/controller/user/UserProjectController.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/ProjectDTO.java
  src/main/java/com/recycle/ecoeco/makerProject/model/dto/RewardDTO.java
  src/main/resources/mappers/user/UserProjectMapper.xml
  src/main/resources/static/css/user/common/footer.css
  src/main/resources/static/css/user/mypage/joinus.css
  src/main/resources/static/css/user/mypage/login.css
  src/main/resources/static/css/user/mypage/searchid.css
  src/main/resources/static/css/user/mypage/searchinfo.css
  src/main/resources/static/css/user/sub/detail/detail.css
  src/main/resources/static/css/user/sub/reward/reward.css
  src/main/resources/static/images/user/common/modal_cancel.png
  src/main/resources/templates/joinus.html
  src/main/resources/templates/login.html
  src/main/resources/templates/main.html
  src/main/resources/templates/manager/ordertab/order/order_info.html
  src/main/resources/templates/user/category.html
  src/main/resources/templates/user/common/footer.html
  src/main/resources/templates/user/mypage/findId.html
  src/main/resources/templates/user/mypage/findPwd.html
  src/main/resources/templates/user/mypage/mypage_MyprojectList_Detail.html
  src/main/resources/templates/user/mypage/news.html
  src/main/resources/templates/user/mypage/registNews.html
  src/main/resources/templates/user/mypage/registNewsDetail.html
  src/main/resources/templates/user/project/detail/detail.html
  src/main/resources/templates/user/project/reward/reward.html
  src/main/resources/templates/user/section.html
Labels: 김동일, 오류수정햇슈
